### ISSUE TITLE
Ctrl-n on the last item should select the first

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#14]
A lot of the times the file I actually want to open is at the top but Niffler selects the bottom one by default. Right now if I hit ctrl-n nothing happends and I have to hit ctrl-p a lot of times or write a longer filter string. Would be a lot simpler if ctrl-n just selected the first line if you're at the last one. The same thing should happen if you're at the first one and hit ctrl-p.

**Comment by pgdouyon** [comment]
Yea I definitely agree, this has actually been bugging me a lot lately.  I'll push out a fix later tonight or tomorrow.  I don't think it should be too difficult.

**Comment by pgdouyon** [comment]
Should be implemented now, let me know if you run into any problems with it.
