### ISSUE TITLE
Highlighting of line endings when niffler window opens

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#16]
If you've got other windows open in splits and you open the niffler window with for example `:Niffler .` the other windows gets their line-endings highlighted. I'm not sure why but it's as if a /search has been made.

![image](https://cloud.githubusercontent.com/assets/19663/7159268/46d7cb7a-e381-11e4-8bd4-0f2df8f98920.png)

This is low-priority but I thought I would bring it up.

**Comment by pgdouyon** [comment]
Sorry about that, that was me being stupid and temporarily forgetting that `:substitute` modifies the search history.  Should be fixed now.
