### ISSUE TITLE
Running Niffler when window is scrolled to the right

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#18]
If you open a file with a long line and scroll the window all to the right and then open Niffler, nifflers window is also scrolled to the right so you can't see the filenames. I guess we just need to make sure the window is at its default position.

**Comment by marlun** [comment]
Just adding the following seem to fix the problem.

``` diff
diff --git a/plugin/niffler.vim b/plugin/niffler.vim
index 0bd859e..e4bbd4b 100644
--- a/plugin/niffler.vim
+++ b/plugin/niffler.vim
@@ -251,6 +251,7 @@ endfunction
 function! s:open_niffler_buffer()
     let origin_buffer = bufname("%")
     keepalt keepjumps edit __Niffler__
+    normal 0
     let b:niffler_origin_buffer = origin_buffer
 endfunction
```

**Comment by pgdouyon** [comment]
That's really weird.  I have no idea why the `call cursor(1, 1)` line doesn't fix this, even with a `redraw!` command following it.  Maybe it's a bug in Vim, no clue if that's expected behavior or not.  I'll push the fix up now, thanks for tracking this down!

**Comment by marlun** [comment]
Great job! With these last couple of fixes Niffler really feels solid, been working really great for me. Thanks @pgdouyon for creating it in the first place :smile: (just wanted to show my appreciation)

**Comment by pgdouyon** [comment]
No problem!  I'm just glad someone else is getting some use out of it besides me.  I'll probably take care of some of the other open issues this weekend.  I got sidetracked the last couple of weeks with work and then trying to learn the Nim language on the side.
