### ISSUE TITLE
Seeing a lot of flickering of vim when moving cursor

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#19]
I'm seeing a lot of flickering of vim when moving the cursor with for example `CTRL-N/P`. When using 'cursorline' and moving the cursor it updates fine so there should be something we can do about it? :) I guess it's when `redraw!` is called (?) but 'cursorline' probably use similar code?

Or is this something that only happens for me because of some external cause?

**Comment by pgdouyon** [comment]
Should be fixed now.  Can you update to the latest and let me know if you still see the flickering?

**Comment by marlun** [comment]
Much better now, thanks!

All I have now is that when I move the cursor the first letter on the next line flashes as if the cursor is on it for 2 milliseconds :smile: not sure if that explains it very good, can make a video if you'd like?

If I've got a vertical split and I open Niffler in the left window the bar (|) in the split line or whatever it's called flashes instead of the first leter of the next line.

If I open Niffler in the right split instead it's the first character in the first column of the left split which flashes.

**Comment by pgdouyon** [comment]
Hmm I don't see any flashing when I run it.  Can you upload a video of the problem?  Alternatively, you could also try it with a minimal vimrc that just loads Niffler.  If the flashing doesn't happen in that case, then it could be due to some other setting/plugin.

**Comment by marlun** [comment]
I tried only loading Niffler and it's not as noticeable as it is with my colorscheme but it's still there, will upload video tomorrow, need to go to bed now.

**Comment by marlun** [comment]
Here's a video showing it: https://cloudup.com/chJSU2kob3J

**Comment by pgdouyon** [comment]
Ohhh yea I've seen that problem before and it used to really annoy me, although it hasn't happened for me in a while not sure why.  I think it's a problem with Neovim's new TUI, I'm guessing there might still be some rendering bugs to work out.

Which version of Neovim are you running?  I'm currently running e1bac3b compiled on April 8 and I don't see the flicker, also looks like we're using the same OS/Terminal emulator so I'm guessing that's not a factor.  Does this also happen for you on Vim or do you only see the flicker in Neovim?

**Comment by marlun** [comment]
neovim --version says commit: d22f2f94047a5ed1e930ee46d0d2e8d6aacfa104 (Tue Apr 14)

It does _not_ happen in regular vim.
