### ISSUE TITLE
API Change: Proposal to remove -new and -all options from :Niffler

### ISSUE THREAD

**Issue by pgdouyon** [pgdouyon/vim-niffler#23]
@marlun let me know if you use the -new or -all options for the :Niffler command.  I'm planning to remove them to both:
1) simplify the API
2) open up the possibility to use other file indexing tools with Niffler (mainly in the case of adding a g:niffler_user_command variable in #8 )

It's difficult to use other file indexing tools because many (like Ag or Pt) can't generate a list of directories, only a list of files.  So it would be confusing to try and use them for the file list generated from the `:Niffler` command but be unable to use it for the directory list generated by the `:Niffler -new` command.  Seems to me like it's more of a misfeature and is complicating the API.

**Comment by marlun** [comment]
I'm not using it so I wouldn't complain if you remove them to improve/simplify the API. I'm all for it.

I've been thinking I'd like a way to search through all my vimwiki files but havn't gotten to it yet but I suspect I'd use some custom command feature :smile:
