### ISSUE TITLE
Add a note about empty result

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#26]
When for example you use `NifflerTags` and the filter returns an empty result there's just an empty buffer shown which can be confusing if you forgot that you opened Niffler :smile: Maybe you could add some text or some hint about it?

**Comment by pgdouyon** [comment]
@marlun 
Yea that's a great idea, might as well extend it to the other Niffler commands while I'm at it

Also, I just saw your comment on the Neovim Gitter channel and it's definitely Niffler that messed that up, completely forgot to reset hlsearch for some reason.  I'll push a fix now.

**Comment by marlun** [comment]
Oh, I actually had a feeling it could be Niffler since I remember you made some commits about resetting options a couple of days ago :smile: Will wait for your fix until I continue my debugging then (wasn't actually debugging, I'm about to stuff me full of strawberries :strawberry:)!

Extending it to all commands seems like a good idea!

**Comment by pgdouyon** [comment]
Oh no you can go ahead and update to the latest, I pushed the fix hours ago =)

**Comment by pgdouyon** [comment]
Hmm I just realized that I might have been confused at your initial request.  

Just to clarify are you suggesting adding a note when there are no initial candidates (files or tags) to populate the list immediately after calling NifflerX **OR** suggesting adding a note when there are no remaining candidates that match the query string after filtering the list?

The first one is easy, the second one potentially prohibitively tricky :disappointed:

**Comment by marlun** [comment]
I was thinking about the second one :smile: however I don't feel it's warranted if it's too complex because it really is just a nice to have feature, no show stopper.

Could possibly even be confusing if it looks like match instead of a note that the filter got no result. Should maybe be colored using the Warning highlight group if done.
