### ISSUE TITLE
Showing only filename in NifflerTags

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#31]
Do we really need to show the whole file path when running NifflerTags? When opening in a split it's impossible to see the function signature unless your file is in the root :smile: When I do it in my current code base I just see similar part of the path which is the same for both files so I can't differentiate between the files.

Wouldn't it be enough to just show the filename? How often do you have the same tag with the same signature in files named the same?

```
member  filename.ext  function(param1, param2) {
```

compared to

```
member  /long/long/long/long/long/very/long/filename.ext  function(param1, param2) {
```

**Comment by pgdouyon** [comment]
> How often do you have the same tag with the same signature in files named the same?

Hmmm you have a good point there.  Let me think about this one for a bit, but it sounds like a good suggestion to me.

**Comment by pgdouyon** [comment]
Managed to figure out a solution to this one using the 'conceal' feature, I think it was introduced in version 7.3.  It's a bit hackish, really ugly, and it messes up the column layout somewhat but overall I think it's a good improvement.  Let me know if you notice any regressions.
