### ISSUE TITLE
Other file commands than open

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#32]
This is more a request for discussion than implementation. What about adding the ability to add custom commands on files. For example I might want to bdelete a buffer (or selection of buffers) when using NifflerBuffer. I don't like the idea of adding more commands by default but a way of adding them yourself might be interesting?

**Comment by pgdouyon** [comment]
Couldn't this be achieved using `niffler#custom()`?

Something like:

``` vim
command -nargs=0 NifflerBDelete call niffler#custom({
    \ "source" : GetBufList(), "sink" : "bdelete"})

function! GetBufList()
  redir => buffers | silent ls | redir END
  return map(split(buffers, "\n"), 'matchstr(v:val, ''"\zs[^"]\+\ze"'')')
endfunction
```

Granted, the code to actually fetch the buffer list is ugly, but you only have to write it once.

**Comment by marlun** [comment]
I never have time to do much viml code, I look into it from time to time but those times are too far apart :)

So "sink" is the command that will be used with the selected files? I'm guessing that "sink" is some default word used in this context? :)

**Comment by pgdouyon** [comment]
That's pretty much it, "sink" is just a Niffler convention and it expects the value stored under the "sink" key to be either a String of a Funcref.  If it's a String, Niffler interprets it as a command and executes that command with the selected line as argument.  If it's a Funcref, Niffler calls the function, passing the selection as the argument.

VimL itself isn't too bad, but there are a lot of weird/obscure parts that can be hard to figure out if you don't know the answer (like getting the buffer list).  That particular snippet of code though is what Niffler uses to grab the buffer list so it should work.  Unfortunately, Vim doesn't provide a function to give you the buffer list so you have to use `:redir` as a bit of a hack.

If you want to write VimL I would recommend skimming:
`:h script` - very long, but this file is essentially the VimL spec.
`:h function-list`
`:h :redir`
`:h :execute`
`:h :normal`

I also can't recommend [Learning Vimscript the Hard Way](http://learnvimscriptthehardway.stevelosh.com/) enough, which is what I used to start learning VimL.

**Comment by marlun** [comment]
Closing this since you've given a good answer.
