### ISSUE TITLE
Errors when using together with neomake

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#43]
When using Niffler together with Neomake I'm getting errors when switching files. The problem can be seen here https://github.com/neomake/neomake/issues/883

Since it seems to be something with matches I'm not sure if it's something similar to https://github.com/pgdouyon/vim-niffler/issues/15

Any ideas? :)

**Comment by pgdouyon** [comment]
Can you try the latest commit and let me know if that fixes it?

**Comment by marlun** [comment]
Seems to work great! Thanks! 🎉
