### ISSUE TITLE
Adding just a space in a Niffler window

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#45]
If I run niffler and just hit SPACE I get:

    || Error detected while processing function
    /Users/.../vim-niffler/autoload/niffler.vim|26| niffler#niffler[12]
    /Users/.../vim-niffler/autoload/niffler.vim|353| <SNR>56_keypress_event_loop[7]
    /Users/.../vim-niffler/autoload/niffler.vim|365| <SNR>56_update_prompt[3]
    /Users/.../vim-niffler/autoload/niffler.vim|625| <SNR>56_filter_candidate_list[10]
    /Users/.../vim-niffler/autoload/niffler.vim|653| <SNR>56_display[2]
    /Users/.../vim-niffler/autoload/niffler.vim|666| <SNR>56_preprocess_candidate_list[6]
    /Users/.../vim-niffler/autoload/niffler.vim|674| <SNR>56_sort_by_mru[1]
    /Users/.../vim-niffler/autoload/niffler.vim|689| <SNR>56_get_candidate_set[2]
    || E714: List required
    || Error detected while processing function
    /Users/.../vim-niffler/autoload/niffler.vim|26| niffler#niffler[12]
    /Users/.../vim-niffler/autoload/niffler.vim|353| <SNR>56_keypress_event_loop[7]
    /Users/.../vim-niffler/autoload/niffler.vim|365| <SNR>56_update_prompt[3]
    /Users/.../vim-niffler/autoload/niffler.vim|625| <SNR>56_filter_candidate_list[10]
    /Users/.../vim-niffler/autoload/niffler.vim|654| <SNR>56_display[3]
    || E712: Argument of map() must be a List or Dictionary

**Comment by pgdouyon** [comment]
Interesting, seems to be a bug in Vim but not Neovim which explains why I haven't run into it before.  I'll see if I can track down the cause.

**Comment by pgdouyon** [comment]
Can you try pulling the latest and verifying that it fixes the problem for you?

**Comment by marlun** [comment]
Seems to work great, thanks! :)
