### ISSUE TITLE
Opening running terminal buffers creates a new buffer with the same name

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#47]
If I use `:NifflerBuffer` to open a running terminal window Niffler seem to open a new buffer instead of showing the terminal buffer. It works great if I open the buffer using the normal vim `:buffer` command.

Steps:
1. Open some file in vim
2. Open a terminal with :terminal
3. Move to the other buffer and run `ctrl-w o`
4. Run `NifflerBuffer` and open the terimal window
5. Now you have some weird buffer which is not the terminal buffer but has the same name

**Comment by pgdouyon** [comment]
Should be fixed now, can you pull the latest and let me know if the problem persists?

**Comment by marlun** [comment]
It's working, thanks once again for solving my problems so fast 🤗🎉
